# Generated by Django 4.1.2 on 2022-12-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
